filer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('searcher.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searcher/urls.py
from django.conf.urls import url

from . import views


app_name = 'searcher'
urlpatterns  = [
    url(r'^searcher-admin/login$', views.login_view, name='login'),
    url(r'^searcher-admin/logut$', views.logout_view, name='logout'),
    url(r'^searcher-admin$', views.view_folder, name='view_folder'),
    url(r'^searcher-admin/(?P<current_folder_id>[0-9]*)$', views.view_folder, name='view_folder'),
    url(r'^searcher-admin/(?P<folder_id>[0-9]+)/change$', views.change_folder, name='change_folder'),
    url(r'^searcher-admin/file/(?P<file_id>[0-9]+)/change$', views.change_file, name='change_file'),
    url(r'^searcher-admin/search$', views.search, name='search'),
    url(r'^search_ajax/$', views.search_ajax, name='search_ajax'),
    url(r'^search$', views.user_search, name='user_search'),
]

searcher/models.py
import os, shutil
from django.db import models
from django.conf import settings
from django.dispatch import dispatcher
import datetime as dt


def get_file_path(instance, filename):
    return instance.get_rel_path() + "/" + instance.upload.name

# Create your models here.
class Folder(models.Model):
    name = models.CharField(max_length=300)
    parrent = models.ForeignKey("self", on_delete=models.CASCADE, null=True)
    tags = models.TextField(null=True)

    class Meta:
        verbose_name = 'Папка'
        verbose_name_plural = 'Папки'

    def __str__(self):
        return self.name

    def get_rel_path(self):
        path = ""
        current_folder = self.parrent
        while current_folder != None:
            path = current_folder.name + "/" + path
            current_folder = current_folder.parrent
        return "root" + "/" + path
    
    def get_abs_path(self):
        return settings.MEDIA_ROOT + self.get_rel_path()
    
    def real_create(self):
        directory = self.get_abs_path() + self.name + "/"
        if not os.path.exists(directory):
            os.makedirs(directory)
    
    def real_delete(self):
        directory = self.get_abs_path() + self.name + "/"
        shutil.rmtree(directory)


class File(models.Model):
    parrent = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True)
    upload = models.FileField(upload_to=get_file_path)
    tags = models.TextField(null=True)

    def get_rel_path(self):
        if self.parrent == None:
            return "root/"
        else:
            return self.parrent.get_rel_path() + self.parrent.name + "/"

    def get_proper_name(self):
        return self.upload.name.split("/")[-1]

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файли'
    
    def __str__(self):
        return self.upload.name

searcher/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Користувач", max_length=300)
    pswd = forms.CharField(label="Пароль", widget=forms.PasswordInput())


class AddFolderForm(forms.Form):
    name = forms.CharField(label="Назва", max_length=300)
    tags = forms.CharField(label="Теги", widget=forms.Textarea, required=False)


class AddFileForm(forms.Form):
    """
    Add file form
    """
    file = forms.FileField()
    tags = forms.CharField(label="Теги", widget=forms.Textarea, required=False)


class DeleteForm(forms.Form):
    """
    Delete form
    """
    def __init__(self, *args, **kwargs):
        folders = kwargs.pop('folders')
        files = kwargs.pop('files')
        super(DeleteForm, self).__init__(*args, **kwargs)
        for folder, folder_field in folders:
            self.fields[folder_field] = forms.BooleanField(required=False)
        for file_, file_field in files:
            self.fields[file_field] = forms.BooleanField(required=False)


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=300, 
        widget=forms.TextInput(attrs={'id':'search-text', 'placeholder': 'Пошук...', 'required': False,})
        )


class ChangeFolderForm(forms.Form):

    def __init__(self, *args, **kwargs):
        folder = kwargs.pop("folder")
        super(ChangeFolderForm, self).__init__(*args, **kwargs)
        self.fields["name"] = forms.CharField(label="Назва", initial=folder.name)
        self.fields["tags"] = forms.CharField(label="Теги", widget=forms.Textarea, required=False, initial=folder.tags)

class ChangeFileForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        file = kwargs.pop("file")
        super(ChangeFileForm, self).__init__(*args, **kwargs)
        self.fields["tags"] = forms.CharField(label="Теги", widget=forms.Textarea, required=False, initial=file.tags)

searcher/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .models import Folder, File
from .forms import AddFolderForm, AddFileForm, DeleteForm, SearchForm, ChangeFolderForm, ChangeFileForm, LoginForm
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy


def tupalize(seq, name):
    return list(map(lambda x: (x, name + str(x.id)), seq))


def get_breadcrumbs(folder_id):
    breadcrumbs = []
    if folder_id:
        current_folder = Folder.objects.get(id=folder_id)
    else:
        return breadcrumbs
    while current_folder != None:
        breadcrumbs.append((current_folder.id, current_folder.name))
        current_folder = current_folder.parrent
    return breadcrumbs


def add_folder(request, context):
    if context["add_folder_form"].is_valid():
        new_context = context
        data = context["add_folder_form"].cleaned_data
        current_folder_id = context["current_folder_id"]
        name = data["name"]
        tags = data["tags"]
        if not Folder.objects.filter(name=name).filter(parrent__id=current_folder_id) and "\\" not in name and "/" not in name:
            if current_folder_id:
                current_folder = Folder.objects.get(id=current_folder_id)
                new_folder = Folder(name=name, tags=tags, parrent=current_folder)
            else:
                new_folder = Folder(name=name, tags=tags, parrent=None)
            new_folder.save()
            new_folder.real_create()
            files = tupalize(File.objects.filter(parrent__id=current_folder_id), "file_")
            folders = tupalize(Folder.objects.filter(parrent__id=current_folder_id), "folder_")
            delete_form = DeleteForm(request.POST or None, folders=folders, files=files)
            new_context.update({"folders":folders,"delete_form":delete_form})
            return render(request, "searcher/view_folder.html", new_context)


def add_file(request, context):
    if context["add_file_form"].is_valid():
        new_context = context
        current_folder_id = context["current_folder_id"]
        tags = context["add_file_form"].cleaned_data["tags"]
        if current_folder_id:
            current_folder = Folder.objects.get(id=current_folder_id)
            file = File(upload=request.FILES['file'], parrent=current_folder, tags=tags)
        else:
            file = File(upload=request.FILES['file'], parrent=None, tags=tags)
        file.save()
        files = tupalize(File.objects.filter(parrent__id=current_folder_id), "file_")
        folders = tupalize(Folder.objects.filter(parrent__id=current_folder_id), "folder_")
        delete_form = DeleteForm(request.POST or None, folders=folders, files=files)
        new_context.update({"files":files,"delete_form":delete_form})
        return render(request, "searcher/view_folder.html", new_context)


def delete(request, context):
    new_context = context
    current_folder_id = context["current_folder_id"]
    if context["delete_form"].is_valid():
        cleaned_data = context["delete_form"].cleaned_data
        for file_, file_field in context["files"]:
            if file_field in request.POST:
                file_.delete()
        for folder, folder_field in context["folders"]:
            if folder_field in request.POST:
                folder.delete()
                folder.real_delete()
        files = tupalize(File.objects.filter(parrent__id=current_folder_id), "file_")
        folders = tupalize(Folder.objects.filter(parrent__id=current_folder_id), "folder_")
        delete_form = DeleteForm(request.POST or None, folders=folders, files=files)
        new_context.update({"files":files, "folders":folders, "delete_form":delete_form})
        return render(request, "searcher/view_folder.html", new_context)


#--------------------------------------------------------------------------------------------------
# Admin views


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        username = data['username']
        pswd = data['pswd']
        user = authenticate(request, username=username, password=pswd)
        if user is not None:
            login(request, user)
            return redirect('searcher:view_folder')
    context = {'form':form}
    return render(request, 'searcher/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('searcher:login')


@user_passes_test(lambda u: u.is_active and u.is_superuser, login_url=reverse_lazy('searcher:login'))
def view_folder(request, current_folder_id=None):
    current_folder_name = None
    if current_folder_id:
        current_folder_name = Folder.objects.get(id=current_folder_id).name
    folders = tupalize(Folder.objects.filter(parrent__id=current_folder_id), "folder_")
    files = tupalize(File.objects.filter(parrent__id=current_folder_id), "file_")
    add_folder_form = AddFolderForm(request.GET)
    add_file_form = AddFileForm(request.POST or None, request.FILES or None)
    delete_form = DeleteForm(request.POST or None, folders=folders, files=files)
    search_form = SearchForm(request.GET or None)
    breadcrumbs = list(reversed(get_breadcrumbs(current_folder_id)[1:]))
    context = {
        "folders":folders,
        "files":files,
        "add_folder_form":add_folder_form, 
        "add_file_form":add_file_form,
        "search_form":search_form,
        "delete_form":delete_form,
        "current_folder_id":current_folder_id,
        "current_folder_name":current_folder_name,
        "breadcrumbs":breadcrumbs,
        "MEDIA_URL":settings.MEDIA_URL,
    }
    add_folder(request, context)
    add_file(request, context)
    delete(request, context)
    return render(request, "searcher/view_folder.html", context)


@user_passes_test(lambda u: u.is_active and u.is_superuser, login_url=reverse_lazy('searcher:login'))
def change_folder(request, folder_id):
    folder = Folder.objects.get(id=folder_id)
    form = ChangeFolderForm(request.POST or None, folder=folder)
    if form.is_valid():
        new_name = form.cleaned_data["name"]
        new_tags = form.cleaned_data["tags"]
        folder.name = new_name
        folder.tags = new_tags
        folder.save()
        if folder.parrent:
            return redirect('searcher:view_folder', folder.parrent.id)
        else:
            return redirect('searcher:view_folder')
    context = {"form":form, "folder":folder}
    return render(request, "searcher/change_folder.html", context)


@user_passes_test(lambda u: u.is_active and u.is_superuser, login_url=reverse_lazy('searcher:login'))
def change_file(request, file_id):
    file = File.objects.get(id=file_id)
    form = ChangeFileForm(request.POST or None, file=file)
    if form.is_valid():
        new_tags = form.cleaned_data["tags"]
        file.tags = new_tags
        file.save()
        if file.parrent:
            return redirect('searcher:view_folder', file.parrent.id)
        else:
            return redirect('searcher:view_folder')
    context = {"form":form, "file":file}
    return render(request, "searcher/change_file.html", context)


@user_passes_test(lambda u: u.is_active and u.is_superuser, login_url=reverse_lazy('searcher:login'))
def search(request):
    search_form = SearchForm(request.GET or None)
    context = {"search_form":search_form, "MEDIA_URL":settings.MEDIA_URL}
    search = request.GET["search"]
    search_list = search.split()
    if search_list:
        folders = set(Folder.objects.filter(tags__icontains=search_list[0]))
        files = set(File.objects.filter(tags__icontains=search_list[0]))
        for word in search_list[1:]:
            folders.intersection_update(Folder.objects.filter(tags__icontains=word))
            files.intersection_update(File.objects.filter(tags__icontains=word))
        folders = tupalize(folders, "folder_")
        files = tupalize(files, "file_")
        context.update({"folders":folders, "files":files})
        return render(request, "searcher/search.html", context)
    else:
        folders = tupalize(Folder.objects.all(), "folder_")
        files = tupalize(File.objects.all(), "file_")
        context.update({"folders":folders, "files":files})
        return render(request, "searcher/search.html", context)


#--------------------------------------------------------------------------------------------------
# User views

def user_search(request):
    form = SearchForm(request.POST or None)
    context = {'form':form, "MEDIA_URL":settings.MEDIA_URL,}
    return render(request, 'searcher/index.html', context)


def search_ajax(request):
    if request.method == 'GET':
        search_text = request.GET.get('search_text')
        search_list = search_text.split()
        response_data = {}
        if search_list:
            folders = set(Folder.objects.filter(tags__icontains=search_list[0]))
            files = set(File.objects.filter(tags__icontains=search_list[0]))
            for word in search_list[1:]:
                folders.intersection_update(Folder.objects.filter(tags__icontains=word))
                files.intersection_update(File.objects.filter(tags__icontains=word))
            folders = [{'id':f.id, 'name':f.name} for f in folders]
            files = [{'id':f.id, 'name':f.get_proper_name()} for f in files]
            response_data.update({'folders':folders, 'files':files})
        return JsonResponse(response_data)
    else:
        return JsonResponse({})

searcher/templates/searcher/base.html
<!DOCTYPE html>
{% load static %}


<head>
  <meta charset="utf-8">
  <meta name="description" content="searcher">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} Filer {% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{{ MEDIA_URL }}/favicon.ico" />
  <!-- Bootstrap core CSS-->
  <link href="{% static 'searcher/vendor/bootstrap/css/bootstrap.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'searcher/vendor/bootstrap/css/bootstrap-theme.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'searcher/vendor/bootstrap/css/bootstrap-theme.css.map' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'searcher/vendor/bootstrap/css/bootstrap.css.map' %}" type="text/css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <script defer src="{% static 'searcher/vendor/font-awesome/fontawesome-all.js' %}"></script>
  <!-- Page level plugin CSS-->
  <link href="{% static 'searcher/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'searcher/css/style.css' %}" rel="stylesheet">

</head>


<body >
  <div>
    <div class="container-fluid">
      {% block root %} {% endblock %}
      {% block search %} {% endblock %}
      {% block change_folder %} {% endblock %}
      {% block login %}{% endblock %}
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'searcher/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'searcher/vendor/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'searcher/vendor/bootstrap/js/npm.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'searcher/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'searcher/vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'searcher/vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'searcher/js/table.js' %}"></script>
    <script src="{% static 'searcher/js/modals.js' %}"></script>
    <script src="{% static 'searcher/js/custom_stuff.js' %}"></script>
  </div>
</body>
</html>

searcher/templates/searcher/change_file.html
{% extends 'searcher/base.html' %}

{% block title %} Редагувати {{ file.name }} {% endblock %}

{% block change_folder %}

{% load searcher_extras %}

{% load static %}

<p></p>

<form method="post" action="">
{% csrf_token %}

        <table align="center">
            <tr>
                <td> {{ file.get_rel_path }}{{ file.get_proper_name }} </td>
            </tr>
            <tr>
                <td> {{ form.tags.label }} </td> <td> {{ form.tags }} </td>
            </tr>
            <tr>
                <td> <p> </td>
            </tr>
            <tr>
                <td> <input type="submit" value="Зберегти" class="btn btn-outline-success"> </td>
                <td> <a href="{% url 'searcher:view_folder' file.parrent.id %}" ><button type="button" class="btn btn-outline-secondary">Відміна</button></a> </td>
            </tr>
        </table>

</form>

{% endblock %}

searcher/templates/searcher/change_folder.html
{% extends 'searcher/base.html' %}

{% block title %} Редагувати {{ folder.name }} {% endblock %}

{% block change_folder %}

{% load searcher_extras %}

{% load static %}

<p></p>

<form method="post" action="">
{% csrf_token %}

        <table align="center">
            <tr>
                <td> {{ form.name.label }} </td> <td> {{ form.name }} </td>
            </tr>
            <tr>
                <td> {{ form.tags.label }} </td> <td> {{ form.tags }} </td>
            </tr>
            <tr>
                <td> <p> </td>
            </tr>
            <tr>
                <td> <input type="submit" value="Зберегти" class="btn btn-outline-success"> </td>
                <td> <a href="{% url 'searcher:view_folder' folder.parrent.id %}" ><button type="button" class="btn btn-outline-secondary">Відміна</button></a> </td>
            </tr>
        </table>

</form>

{% endblock %}

searcher/templates/searcher/search.html
{% extends 'searcher/base.html' %}

{% block title %} search {% endblock %}

{% block search %}

{% load searcher_extras %}

{% load static %}

<p> </p>

<div style="text-align: left"> <a href="{% url 'searcher:view_folder' %}" > Повернутися до адміністрування директорій </a> </div>

<p> </p>


<div class="card mb-3">
    <div class="card-header">
        <table style="width: 100%;">
            <tr>
                <td style="text-align: center;">
                    <div class="search-container">
                        <form method="get" action="">
                            {{ search_form.search }}
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-body">
        <div class="table-responsive">
    
            <form method="post">
                {% csrf_token %}
                <table class="table table-striped table-bordered" id="file_table">
	                <thead>
		                <tr>
                            <th scope="col"> # </th>
        	                <th scope="col"> Назва </th>
                            <th scope="col"> Теги </th>
                            <th scope="col"> Місцезнаходження </th>
                            <th scope="col">  <i class="fas fa-edit"></i> </th>
		                </tr>
	                </thead>
	                <tbody>
                        {% for folder, folder_field in folders %}
                        <tr>
                            <td> <i class="far fa-folder"></i> </td>
                            <td> <a href="{% url 'searcher:view_folder' folder.id %}"> {{ folder.name }}</a> </td>
                            <td> {{ folder.tags }} </td>
                            <td> <a href = "{% url 'searcher:view_folder' folder.parrent.id %}" > {{ folder.get_rel_path }} </a> </td>
                            <td> <a href="{% url 'searcher:change_folder' folder.id %}"><i class="fas fa-pencil-alt"></i></a> </td>
                        </tr>                        
                        {% endfor %}
                        {% for file, file_field in files %}
                        <tr>
                            <td> <i class="fas fa-file"></i> </td>
                            <td> {{ file.get_proper_name }} <a href="{{ MEDIA_URL }}{{file.upload.name}}" download><i class="fas fa-download"></i></a> </td>
                            <td> {{ file.tags }} </td>
                            <td> <a href="{% url 'searcher:view_folder' file.parrent.id %}"> {{ file.get_rel_path }} </a> </td>
                            <td> <a href="{% url 'searcher:change_file' file.id %}"><i class="fas fa-pencil-alt"></i></a> </td>
                        </tr>                        
                        {% endfor %}
	                </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

{% endblock %}

searcher/templates/searcher/user-search.html
<!DOCTYPE html>
{% load static %}

  <head>
    <meta charset="utf-8">
    <meta name="description" content="searcher">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Filer {% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{{ MEDIA_URL }}/favicon.ico" />
    <!-- Custom fonts for this template-->
    <script defer src="{% static 'searcher/vendor/font-awesome/fontawesome-all.js' %}"></script>
  </head>


  <body>

    <form action="/create_post/" method="GET" id="search-form">
      {{ form.search }}
      <button type="submit"><i class="fa fa-search"></i></button>
      <div id="results"></div> <!-- errors go here -->
    </form>

    <!-- Here is code for displaying search results -->
    <ul id=search_result>

    </ul>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'searcher/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'searcher/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'searcher/vendor/jquery-easing/jquery.easing.min.js' %}"></script>


    <!-- ajax for dynamic search -->
    <script>
        // AJAX for posting
        function search() {
            console.log("search is working!") // sanity check
            $.ajax({
                url : "{% url 'searcher:search_ajax' %}", // the endpoint
                type : "GET", // http method
                data : { search_text : $('#search-text').val() }, // data sent with the post request

                // handle a successful response
                success : function(json) {
                    $('#search-text').val(''); // remove the value from the input
                    console.log(json); // log the returned json to the console
                    console.log("success"); // another sanity check
                    var folders = "";
                    for (var f in json.folders)
                    {
                        folders = folders + "<li> Папка: " + json.folders[f].name + "</li>";
                    }
                    var files = "";
                    for (var f in json.files)
                    {
                        files = files + "<li> Файл: " + json.files[f].name + "</li>";
                    }
                    $('#search_result').empty();
                    $('#search_result').append(folders, files);
                },

                // handle a non-successful response
                error : function(xhr,errmsg,err) {
                    $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                        " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        };

        // Submi search on submit
        $('#search-form').on('submit', function(event){
            event.preventDefault();
            console.log("form submitted!")  // sanity check
            search();
        });

    </script>

  </body>
</html>

searcher/templates/searcher/view_folder.html
{% extends 'searcher/base.html' %}

{% block title %} MO Sirius {% endblock %}

{% block root %}

{% load searcher_extras %}

{% load static %}

<p> </p>

<div style="text-align:right"> <a href="{% url 'searcher:logout' %}">Вийти</a> </div>

<p> </p>

<!-- Breadcrumbs -->
{% if current_folder_id %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'searcher:view_folder' %}">root</a>
    </li>
    {% for folder_id, folder_name in breadcrumbs %}
    <li class="breadcrumb-item">
      <a href="{% url 'searcher:view_folder' folder_id %}">{{ folder_name }}</a>
    </li>
    {% endfor%}
    <li class="breadcrumb-item active"> {{ current_folder_name }} </li>
</ol>
{% else %}
<ol class="breadcrumb">
    <li class="breadcrumb-item active"> root </li>
</ol>
{% endif %}


<!-- The File add modal -->
<div id="add_file_modal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div style="text-align: right;">
            <span class="file_close_btn">&times;</span>
        </div>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <table>
            <tr><td> {{ add_file_form }} </td></tr>
            <tr><td> &nbsp; </td></tr>
            </table>
            <div style="text-align: center;">
                <input type="submit" value="Завантажити" class="btn btn-outline-success">
            </div>
        </form>
    </div>
</div>


<!-- The Folder add modal -->
<div id="add_folder_modal" class="modal">
        <!-- Modal content -->
    <div class="modal-content">
        <div style="text-align: right;">
            <span class="folder_close_btn">&times;</span>
        </div>
        <form method="get">
            <table>
            <tr><td> {{ add_folder_form.name.label }} </td> <td> {{ add_folder_form.name }}</td></tr>
            <tr><td> &nbsp; </td></tr>
            <tr><td> {{ add_folder_form.tags.label }} </td> <td> {{ add_folder_form.tags }}</td></tr>
            <tr><td> &nbsp; </td></tr>
            </table>
            <div style="text-align: center;">
                <input type="submit" value="Створити" class="btn btn-outline-success">
            </div>
        </form>
    </div>
</div>



<div class="card mb-3">
    <div class="card-header">
        <table style="width: 100%;">
            <tr>
                <td style="text-align: left;">
                    <div class="search-container">
                        <form method="get" action="{% url 'searcher:search' %}">
                            {{ search_form.search }} 
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </td>
                <td style="text-align: right;"> 
                    <a id="add_file_btn"> <img class="action_icon" src="{% static 'searcher\img\add_file.png' %}" width="19" height="19"> </a> &nbsp; | &nbsp; 
                    <a id="add_folder_btn"> <img class="action_icon" src="{% static 'searcher\img\add_folder.png' %}" width="30" height="30"> </a> &nbsp; | &nbsp;
                    <a id="del_btn"> <img class="action_icon" src="{% static 'searcher\img\trash.png' %}" width="20" height="20"> </a>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-body">
        <div class="table-responsive">
    
            <form method="post">
                {% csrf_token %}
                <table class="table table-striped table-bordered" id="file_table">
	                <thead>
		                <tr>
                            <th scope="col"> # </th>
        	                <th scope="col"> Назва </th>
                            <th scope="col"> Теги </th>
                            <th scope="col"> <i class="fas fa-edit"></i> </th>
		                </tr>
	                </thead>
	                <tbody>
                        {% for folder, folder_field in folders %}
                        <tr>
                            <td> {{ delete_form|get_field_value:folder_field }} &nbsp; &nbsp;<i class="far fa-folder"></i> </td>
                            <td> <a href="{% url 'searcher:view_folder' folder.id %}"> {{ folder.name }}</a> </td>
                            <td> {{ folder.tags }} </td>
                            <td> <a href="{% url 'searcher:change_folder' folder.id %}"><i class="fas fa-pencil-alt"></i></a> </td>
                        </tr>                        
                        {% endfor %}
                        {% for file, file_field in files %}
                        <tr>
                            <td> {{ delete_form|get_field_value:file_field }} &nbsp; &nbsp; <i class="fas fa-file"></i> </td>
                            <td> {{ file.get_proper_name }} <a href="{{ MEDIA_URL }}{{file.upload.name}}" download><i class="fas fa-download"></i></a> </td>
                            <td> {{ file.tags }} </td>
                            <td> <a href="{% url 'searcher:change_file' file.id %}"><i class="fas fa-pencil-alt"></i></a> </td>
                        </tr>                        
                        {% endfor %}
	                </tbody>
                </table>
                <!-- The delete modal -->
                <div id="del_modal" class="modal">
                    <!-- Modal content -->
                    <div class="modal-content">
                        <div style="text-align: right;">
                            <span class="del_close_btn">&times;</span>
                        </div>
                        <div style="text-align: center;">
                            <input type="submit" name="delete" value="Видалити" class="btn btn-outline-danger"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}